services:

  back:
    image: warden696/node_api_b3:latest
    container_name: back
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  front:
    image: warden696/react_app_b3:latest
    container_name: front
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:14.15-alpine3.21
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: Librario
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db